### ISSUE TITLE
Massive failures when attempting to install on Linux Mint 19.*

### ISSUE THREAD

**Issue by olyerickson** [mpoegel/SemNExT-Visualizations#34]
```
> swot-clock@0.5.0 prestart /home/olyerickson/Desktop/SemNExT-Visualizations
> gulp build

[06:22:58] Using gulpfile ~/Desktop/SemNExT-Visualizations/gulpfile.js
[06:22:58] Starting 'ts'...
[06:22:58] Starting 'bundle-css'...
[06:22:58] Finished 'bundle-css' after 94 ms
src/client/script/helpers/ui.ts(477,33): error TS2339: Property 'files' does not exist on type 'Element'.

[06:23:00] 'ts' errored after 2.32 s
[06:23:00] Error: Command failed: node_modules/.bin/tsc -p src

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)

npm ERR! Linux 5.4.0-42-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! swot-clock@0.5.0 prestart: `gulp build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the swot-clock@0.5.0 prestart script 'gulp build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the swot-clock package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs swot-clock
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls swot-clock
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/olyerickson/Desktop/SemNExT-Visualizations/npm-debug.log

```

**Comment by olyerickson** [comment]
Updated Node.js to current; I now see:
```
olyerickson@Mint-ThinkPad-P51:~/Desktop/SemNExT-Visualizations$ npm start

> swot-clock@0.5.0 prestart /home/olyerickson/Desktop/SemNExT-Visualizations
> gulp build

fs.js:40
} = primordials;
    ^

ReferenceError: primordials is not defined
    at fs.js:40:5
    at req_ (/home/olyerickson/Desktop/SemNExT-Visualizations/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/home/olyerickson/Desktop/SemNExT-Visualizations/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/home/olyerickson/Desktop/SemNExT-Visualizations/node_modules/vinyl-fs/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:1251:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1272:10)
    at Module.load (internal/modules/cjs/loader.js:1100:32)
    at Function.Module._load (internal/modules/cjs/loader.js:962:14)
    at Module.require (internal/modules/cjs/loader.js:1140:19)
    at require (internal/modules/cjs/helpers.js:75:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! swot-clock@0.5.0 prestart: `gulp build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the swot-clock@0.5.0 prestart script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/olyerickson/.npm/_logs/2020-08-22T10_36_12_018Z-debug.log

```
